### ISSUE TITLE
Define EventStore API

### ISSUE THREAD

**Issue by bwaidelich** [neos/Neos.EventStore#1]
The current EventStore API is:

```php
interface EventStoreInterface
{

    public function get(string $identifier): EventStream;

    public function contains(string $identifier): bool;

    public function commit(EventStream $stream): int;
}
```

We should review and re-evaluate that.

**Comment by bwaidelich** [comment]
I especially want to argue about the _retrieval_ of events: I think that we need a little more flexibility here than only to be able to fetch events by the Aggregate identifier (IMO we should even completely remove the notion of "aggregate" from the ES).

## Background

Especially when reconstituting state for _multiple_ aggregates (i.e. for "special" read models, process managers, ...) we can't just replay _all_ events in the store.
Even for a very simple read model that only listens to one event type it would be an overkill to always replay _all_ events of the corresponding aggregate.

## Suggestion

Something along those lines could work:
```php
class EventStreamFilter
{

    /**
     * @var int
     */
    public $minVersion = null;

    /**
     * @var string
     */
    public $streamName = null;

    /**
     * @var string
     */
    public $streamNamePrefix = null;

    /**
     * @var string[]
     */
    public $eventTypes = null;

}
```

And an instance of that filter could be passed to some `read` or `get` function of the ES and then internally transformed to match the configured backend.

**Comment by dfeyer** [comment]
We discuss the topic during the sprint, and yes 👍 to add this flexibility

From my POV, we need min/max version (useful for conflict resolution by ex.) and start/end datetime (storage time), to make it really flexible.

**Comment by albe** [comment]
Yes, querying for event type, min+max version and start/end time are pretty important.

```
class EventStreamFilter
{
    /**
     * @var int
     */
    public $minVersion = null;

    /**
     * @var int
     */
    public $maxVersion = null;

    /**
     * @var \DateTimeImmutable
     */
    public $since = null;

    /**
     * @var \DateTimeImmutable
     */
    public $until = null;

    /**
     * @var string
     */
    public $streamName = null;

    /**
     * @var string
     */
    public $streamNamePrefix = null;

    /**
     * @var string[]
     */
    public $eventTypes = null;
}
```

> IMO we should even completely remove the notion of "aggregate" from the ES

Yes, the EventStore API should be an EventStream that is identified by a name. The Repository would then translate AggregateType + Identifier to a stream name and push and pull EventStreams.

What I found plausible yesterday in addition, would be some "StreamContext", i.e. a stringy value that could act as a partition point in EventStore backend implementations (which will eventually become important for scaling). In DDD it could for example be equivalent to the BC.

So there would be some class like that to identify streams:
```
class EventStreamName
{
    /**
     * @var string
     */
    public $name;

    /**
     * @var string
     */
    public $context;

    public function __toString()
    {
        return $this->context . '-' . $this->name;
    }
}
```

Again, ignore the public properties, the name should be immutable.

**Comment by bwaidelich** [comment]
> we need min/max version

I absolutely see the need for *min* version (to catchup projections for example).
What would you use the *max* version for?

>  useful for conflict resolution by ex.

I *do* think that we need the `expectVersion` parameter when publishing events but I fail to understand how a min/max version for the querying part would solve conflicts.. Could you elaborate?

> start/end datetime (storage time), to make it really flexible.

Why do you think that one is required?
IMO one should never query the ES directly to display a result to the public. And even for debugging/monitoring reasons I would probably always create a corresponding projection and query its state instead.

It's very easy to add filters and in this case very easy to implement them in the doctrine implementation. But keep in mind that we'll need to support everything we make public API in all future versions and adapters so I think it makes sense to collect valid use-cases and possible alternatives before we fall into the YAGNI trap.

I didn't do that above, but let me quickly change that:

### minVersion

Projections should track which events they have processed already. Especially if a projection is executed asynchronously we need a way to process events *after the fact* in order to let the projection *catch up*

### streamName

Usually the stream name is the combination of the aggregate type and its identifier (i.e. `Customer-<uuid>`). In order to reconstitute the state of a particular aggregate, this filter is needed  (and it's the only one we already have with `get($identifier)`)

### streamNamePrefix

A projection is often concerned in events of a given aggregate *type* (i.e. if you have a `Customer` aggregate and a `CustomerListItems`-projection).
Therefore I think that we need a way to read all events for a given prefix (`Customer-` in this case).
Note: In geteventstore.com this is achieved via `fromCategory('Customer')`

### eventTypes

Mostly an internal optimization:
We know which event types an event handler (including projections) listens for, so we could fetch only those events in question when *replaying* events.



For the record: This is mostly based on gut feeling and I'm not saying that this covers all scenarios, but I strongly think that we should only implement features as soon as we actually need them

**Comment by albe** [comment]
> A projection is often concerned in events of a given aggregate type (i.e. if you have a Customer aggregate and a CustomerListItems-projection).

I would even go so far and question if a Projection is ever only interrested in events of a single aggregate **instance**. For that it would need to know the (technical!) identifier of the instance it wants to project for only, which is something I can not imagine a real use-case for.

A Projection IMO normally doesn't event realize the concept of "Aggregate", only implicitly by just listening to Events that a specific Aggregate emits. But I doubt you would want to declaratively create a Projection "listens to (all of) [Aggregate]". Conceptually I think such a tight coupling of read side to the core domain is not necessary or even recommended.

Just imagine the Projection running on a different machine - all it will know is the Events that your domain emits (ie. the public read API).


### maxVersion, until

When replaying Projections for debugging purposes, you are interrested at the state of the Projection at a specific point in time or alternatively a version number.
Those filters can very easily be applied on-top, since they are mostly not time-critical.

**Comment by bwaidelich** [comment]
> I would even go so far and question if a Projection is ever only interrested in events of a single aggregate instance

I could imagine that this could come in handy in domains where you only have a very specific set of aggregates (Imagine for example a wind farm where you need an event stream for each turbine). But anyways, you only seem to support my reasoning from above (or did I miss something?): The stream name (including identifier) is needed not for projections, but to reconstitute the aggregate state (i.e. when loading the aggregate from its repository).

> maxVersion, until [...] you are interrested at the state of the Projection at a specific point in time or alternatively a version number

Good point, that's indeed a valid usecase. To leverage the full debugging power one should also be able to *alter* history (by modifying/removing/adding events). But both not in production but in a "lab" with the copied event stream. So I wonder if we risk misuse when adding it to the API!?

> Those filters can very easily be applied on-top

Yes, I agree. If we have more insight we might consider adding them to a separate interface so we can still have adapters supporting a subset (but this is just thinking out loud, lets see what requirements arise from using this in practice)

**Comment by albe** [comment]
> you only seem to support my reasoning from above

Yep :)

>The stream name (including identifier) is needed not for projections, but to reconstitute the aggregate state (i.e. when loading the aggregate from its repository).

Yes, I would suggest clearly separating the two querying methods (i.e. keep the current `get` and **add** some `find`/`filter`/w\e method that does the querying as required for Projection stuff.

> able to alter history

I would suggest doing this as a middleware to the EventStore - that way you can alter events, but you don't alter the persisted events. If you want to persist the altered Stream, you can do that easily by just calling EventStore:commit with a new stream name (might we need some stream-versioning at a point?).

> So I wonder if we risk misuse when adding it to the API!?

I don't think the plain filtering can be misused. But I'd also be ok with only implementing those additional filters in some "EventStoreDebugger" middleware.

**Comment by dfeyer** [comment]
> I do think that we need the expectVersion parameter when publishing events but I fail to understand how a min/max version for the querying part would solve conflicts.. Could you elaborate?

In conflict resolution, you must query the store to ask what change between version a and b to see if any conflicting event exist, but maybe b is always the most recent version ... so maybe the need of min/max in this case is wrong.

But one use case for the Neos UI, is to compare a node version A with a node version B (diff), so you need this min/max query for this case.

**Comment by dfeyer** [comment]
Currently our EventStream require an aggregate identifier, so the ```filter``` method can return a raw array of events or we need to refactor the EventStream object

**Comment by albe** [comment]
I would start with refactoring the EventStream to be aggregate-agnostic. What exactly is the reason for the EventStreamData container btw?

**Comment by dfeyer** [comment]
@albe Feel free to refactor the EventStream

About the EventStreamData it's just a DTO to transport Event. EventStream has logic to add event, mark applied, ...).

**Comment by dfeyer** [comment]
Basically both should be aggregate agnostic i think

**Comment by dfeyer** [comment]
Now the store is more simple and EventStreamData, EventStream and MessageMetadata are aggregate agnostic, check https://github.com/neos/Neos.EventStore/pull/9

**Comment by bwaidelich** [comment]
Some suggestions for the ES API after playing around with it and some other implementations.
This might get a bit longer, bear with me.

## Event Retrieval

The current API for that is:
```php
public function get(string $streamName): EventStream
```
As discussed above, I'd suggest to replace that with something like
```php
public function get(EventStreamFilter $filter): EventStream
```
Personally I don't think we need a separate method to retrieve events for one aggregate as this is mainly used by the framework anyways and because we could always implement more specific filters like
```php
class AggregateStreamFilter extends EventStreamFilter
{
   public function __construct(AggregateRootInterface $aggregate)
   {
      $this->streamName = ...
```

The `EventStream` that is returned currently has two responsibilities which comes with some problems (e.g. it has `getNewEvents()`, `addEvent()` and `markAllApplied()` all of which are not relevant to the stream returned by the store).
I'd suggest to keep the name (and the fact that it extends `IteratorAggregate`) but turn it into an iterator of `StoredEvent`s (or some better name) that contain a reference to the unserialized `EventInterface` instance and the `EventMetadata` (including version, ...)

## Event publishing

The current API for that is:
```php
public function commit(string $streamName, EventStream $stream, \Closure $callback = null) :int
```

#### string $streamName

I think that's perfectly fine. I've seen [implementations](https://github.com/prooph/event-store/blob/master/src/EventStore.php#L129) where they use a `StreamName` class, but I don't understand why and think it's over-sophisticated.

#### EventStream $stream

Here `EventStream` is the wrong notion IMO. It is _not_ a stream in this case but a fixed set/collection of Events (with usually only one event in it).

I like the [geteventstore-client implementation](https://github.com/FriendsOfOuro/geteventstore-php-core/blob/master/src/EventStoreInterface.php#L41) in that regard: They just have a `WritableToStream` interface that can either be a single event or a collection of events.

#### \Closure $callback

Apart from the naming (what's this closure for?) I hope that we don't need that callback.
We currently use it to add the `version` to the event metadata in `EventSourcedRepository::save()`.
I think that the *stream version* should be a core concept of the ES Event-Metadata and thus be added by the store upon commit.
And other metadata (that might be specific to the application) should be addable via some general "hook" anyways (IMO we could even use Signal/Slots for this).

#### return type int

We don't use it and I don't think we need it.

#### optimistic locking

What I *miss* in the current implementation is a way to implement optimistic locking.
Again, I like how the geteventstore-client implementation solves this:
```php
public function writeToStream(string $streamName, WritableToStream $events, int $expectedVersion = ExpectedVersion::ANY)
````
where `$expectedVersion` is an integer with two special cases:
* `ANY` (-2) is the default and basically disables optimistic locking for that commit
* `NO_STREAM` (-1) expects the event(s) to be the first ones in the stream (useful to avoid clashes when creating new instances)

## Contains

```php
public function contains(string $streamName): bool
```
We only use that to provide `EventSourcedRepository::contains()` but I wonder if we need that.
IMO the code should always know whether an aggregate is expected to exist or not. Or do you have a scenario for this?


Ok, as expected, that turned into a novel..

**Comment by bwaidelich** [comment]
Ah, one thing I forgot to mention:
If we really implement the "filterable"-EventStream we have to keep in mind, that the entries in the result are **deterministic** and have a **sequential version**.
This is very important because every consumer (including Projections) should be able to rely on that (e.g. projections store the last version they have processed and can only replay new events).

Implementation-wise this can be a bit tricky because we must not reuse the event version of the stored event (even though that might also be of interest).
Again, I like how GetEventStore solves this. In their Event Atom Feed one entry looks something like this:
```
{
	"eventId": "ff56b4b5-b940-474b-9f4b-350916de7755",
	"eventType": "Crm:Person:PersonWasCreated",
	"eventNumber": 123,
	"data": "{...}",
	"metaData": "{...}",
	"streamId": "Person-8c5da344-1579-4d43-a350-a3dc6c1e35c0",
	"positionEventNumber": 13,
	"positionStreamId": "$ce-Person",
	// ...
}
```
So they have the `eventNumber` which is the index of the event in it's stream.
But they also have `positionEventNumber` which is the deterministic index of that composite stream (in this case it's a stream over all events of all *Person* aggregates).

**Comment by dfeyer** [comment]
> NO_STREAM (-1) expects the event(s) to be the first ones in the stream (useful to avoid clashes when creating new instances)

@bwaidelich So the expected version will be 1 ... or I miss something ?

**Comment by albe** [comment]
No, it basically expects that no events exist in the stream yet (which is distinct from the events having a specific version).

**Comment by albe** [comment]
> return type int
>
> We don't use it and I don't think we need it.

Well, we will need it if we want to return the commit version from a command, so that the client can later use it for optimistic concurrency - or, what I found a good use with eventual consistency, do queries against a specific commit version. For that the projections just need to store the current commit version they are up-to-date to, then you can easily do following logic in the UI for example:

- send command
- send query against read model
- if query result version is lower than command commit version returned, retry

That way you can have a better UX with fake immediate-consistency, without having to add event-driven notification inside the read side or making the read model strongly consistent.

Also, the commit version can be used for very efficient Cache-Control on the query side.

**Comment by dfeyer** [comment]
> Also, the commit version can be used for very efficient Cache-Control on the query side.

Agree that we need to expose the version

**Comment by dfeyer** [comment]
> No, it basically expects that no events exist in the stream yet (which is distinct from the events having a specific version).

Not sure if I get it ... if the stream is empty ... the first event will have version 1, no ? The storage is responsible to set the version, you just pass an expected version to the commit method to implement optimistic lock ? Or ... i miss something ... those constant refactoring cost me some brain cells ;)

**Comment by albe** [comment]
> if the stream is empty ... the first event will have version 1, no ?

Yes yes, technically it's the same in our case, but conceptually it is a difference between "expect version 1" or "expect empty stream". The first implicates knowledge about the internal versioning system used - imagine the version number just wouldn't start counting at 1, but at 0 - or maybe at 1000 for some reason. In that case "expect version 1" would fail, while "expect empty stream" would succeed if the stream is actually empty.

**Comment by bwaidelich** [comment]
## Expect version

> if the stream is empty ... the first event will have version 1, no ?

No. This is how it works with geteventstore (and IMO it makes a whole lot of sense):
The `expectVersion` specify what version you operate on, not what version you expect as the _resulting_ event. So:

`NO_STREAM (-2)`: There must not be an event in the stream yet
`ANY (-1)`: I don't care
`0`: There's exactly _one_ event in the stream
`1`: There are exactly _two_ events in the stream
...

(note that this is an index that should be 0-based).

## commit() : int

Regarding omitting the return type for  `commit()` I'm surprised that you disagree with me as this is in sync with CQS, the base for CQRS (methods should either have a return value or change state, not both). But lets not focus on the theories but get into it:

> Well, we will need it if we want to return the commit version from a command, so that the client can later use it for optimistic concurrency

Can you elaborate how you would implement optimistic locking from the command?

I totally agree that the Read Models should be able to know what version they represent (as exposing the version to the client is the only way to really ensure optimistic locking) but I don't see how that is related to the ES to return the version.

For me it worked out nicely like this:
During projection we can get the version from the event metadata and we can store it in our Read Model. Then we can pass that version to some `expectVersion` of a command we want to execute on that model:
```html
<f:form action="rename" objectName="command">
  <f:form.hidden property="expectVersion" value="{customer.version}" />
  <f:form.textfield property="newName" />
  <!-- ... -->
</f:form>
```
(whether "expectVersion" is part of the command payload or sent separately doesn't really matter for the point I'm trying to make).

When the aggregate emits the event it _can_ specify the `expectVersion` in order to ensure consistency.

I also fail to understand how a "fake immediate-consistency" can benefit from that:

> if query result version is lower than command commit version returned, retry

Can you provide an example?


Just for the record: I don't think it's a biggy at all to have the ES return the just published event number but I think we should first agree on an implementation of optimistic locking. Maybe we should discuss that in a separate ticket!?

**Comment by albe** [comment]
> The expectVersion specify what version you operate on, not what version you expect as the resulting event.

Ah! That makes a lot of sense!

> Can you elaborate how you would implement optimistic locking from the command?

My idea was, that the optimistic concurrency check starts with a command (ie you only work on command return results), but that was just wrong-thinking I see now. The expected version is set from the read side that shows the form for a command in the first place.
So forget that argument.

> Can you provide an example?

Sure. Say you send a command `PromoteUser`, while at the same time the `User` you are working on has been edited (without conflicts) by someone else (name typo fixed, etc.), so your command passes (or is automatically redispatched after the first optimistic concurrency error). Now you want your UI to query for the new `User` model reflecting the promotion.
For that you send a query `getUserProfileInformation(expectedMinimumVersion)` from your UI after the command was succesfully dispatched with the version returned from the command (the version checking loop can be done client or server side).
If you only do this based on the version you worked on (= read model version) +1, you will probably only get a `UserProfileInformation` with one of the editings that the other person did, but not yet the promotion applied. The user in front of the screen is confused if his last action wasn't correctly applied and reattempts, getting an error back (`User already promoted!`). Shitty UX. So you need the actual version of the aggregate after the commit.

And yes, you are right that this breaks the CQS principle. But it buys a tool for better UX.

**Comment by bwaidelich** [comment]
> Say you send a command PromoteUser [...]

I read it three times but I can't follow your example tbh.. I'll try again with a fresh head tomorrow ;)
But regarding:

> For Projections that work on multiple Aggregates/Aggregate instances, a single aggregate version does not hold any useful information in regard to the Projection version

That's exactly what I was referring to with https://github.com/neos/Neos.EventStore/issues/1#issuecomment-249173650
The `eventNumber` is just the sequence within one stream, but the result of any (filtered) EventStore-Query must contain an incremental, deterministic index.

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#34
