### ISSUE TITLE
Remove EventStreamData and replace usage with EventStream directly

### ISSUE THREAD

**Issue by albe** [neos/Neos.EventStore#10]
EventStreamData is now rather redundant, everything it provides can be done with the EventStream directly.

**Comment by bwaidelich** [comment]
Related to that we should reconsider the naming IMO (as it's part of the public API in this case):
The thing the ES _returns_ is indeed a stream but what you pass it is a _collection_ of events, not a stream

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#38
