### ISSUE TITLE
Allow "manual" publishing of events

### ISSUE THREAD

**Issue by bwaidelich** [neos/Neos.EventStore#13]
Currently the publishing of events is encapsulated in `EventSourcedRepository::save()`:
```php
$this->eventStore->commit($streamName, $stream, function ($version) use ($uncommittedEvents) {
	foreach ($uncommittedEvents as $eventTransport) {
		$eventTransport->getMetaData()->add(Metadata::VERSION, $version);
		$this->eventBus->handle($eventTransport);
	}
});
```
But sometimes it can be useful to be able to publish events directly.
Examples:
* Re-publish events from a 3rd party service (think meteorological data for example, or webhook -> event)
* Assign unique numbers to aggregates as soon as they have been created
* `ProcessManagers`/`Sagas` (although I think that they usually communicate by sending *commands*  to other aggregates)

**Comment by bwaidelich** [comment]
One simple approach could be to make `EventStore` a final class and only abstract it via the `EventStoreBackend` (as it's already done) and then do the publishing to the `EventBus` from there. So sth like
```php
$this->eventStore->publish($streamName, $someEvent);
```
would store the event and publish it (enriched with metadata) to the `EventBus`.
But obviously that would increase coupling and maybe we need to extract that to yet another .. "service"

**Comment by dfeyer** [comment]
> But obviously that would increase coupling and maybe we need to extract that to yet another .. "service"

Break "single responsibility principle" badly

Fine to have an other service, and it's the way to go, because this service will receive the Event enrichment "middleware" in a pluggable way

**Comment by dfeyer** [comment]
> One simple approach could be to make EventStore a final class

Unfortunatly our support for final class is pretty limited, you can not inject a final class :(

**Comment by dfeyer** [comment]
The foundation should be covered by https://github.com/neos/Neos.Cqrs/pull/27/commits/9bcf62e81d854628c99aed20cbd36295bcfd907f

**Comment by bwaidelich** [comment]
> Unfortunately our support for final class is pretty limited

True. It will be fixed with https://github.com/neos/flow-development-collection/issues/496 and I already have that working locally, will push a PR next week. But we can tackle this separately

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#39
