### ISSUE TITLE
Why can events not be stored when there is no associated listeners

### ISSUE THREAD

**Issue by sorenmalling** [neos/Neos.EventStore#19]
Partly mentioned in #8 i will like to open the topic "persisting events even when no listeners".

It is true, that no listeners are located/detected if no class is found implementing the EventListenerInterface and having a method named ex. `whenAccountCreated`.

And as a consequence of that your event will not be persisted to the `es_stream` table when doing the following from your code
```
$eventTransport = EventTransport::create(
            new AccountCreated(
                $account->getAccountIdentifier(),
                $account->getAuthenticationProviderName()
            ),
            new MessageMetadata()
        );
        $this->eventBus->handle($eventTransport);
```
as the `eventBus::handle` does a early return if no listeners are found (edited)

This leaves you with no possibility of having a message queue like "rabbitmq" "beanstalkd" and similar to handle this or simply have events store that have happened at a time, where there might not have been  a concrete listener.

Is there a reasoning for this being to tight coupled and "requiring" everything to happen in sync/at runtime?

**Comment by bwaidelich** [comment]
@sorenmalling Can you please write what you do and what the expected vs actual behavior is?
If you want to *manually* publish events without using a `Repository` have a look at #13

**Comment by dfeyer** [comment]
Good point, from my perspective an Event that don't change the local state (of an aggregate) is not used by the system. 

The current implement doesn't disallow to publish event in a job queue, we just lack the implementation currently.

Currently if you call the Repository->save for your aggregate your event (even with the when method) must be persisted in the EventStore)

Based on the discussion with @bwaidelich we will add a new Service to publish Event directly to the store for side case (importing event from external system, ...). With the service you will have the possibility to store an event that does not have a local aggregate.

**Comment by sorenmalling** [comment]
@bwaidelich In my case I'm creating the exact event as you can see above after a new account is created (authenticated from Facebook OAuth).

I was expecting it to commit to my stream but the method just does a early return as no listener is found.

```
public function handle(EventTransport $transport)
    {
        $listeners = $this->locator->getListeners($transport->getEvent());

        if ($listeners === null) {
            return;
        }
      ...
}
```

**Comment by bwaidelich** [comment]
I think there's some misunderstanding:
We use the `EventBus` to publish events *after* they have been persisted in the ES.
That's what `EventSourcedRepository::save()` does for you.
If this is about publishing events without going through the `Aggregate`/`Repository` way I guess this is a duplicate of #13 indeed

**Comment by sorenmalling** [comment]
This is about publishing a event without having a connection to my own aggregate (I guess that you can say the `Account` model of the Flow package is a aggregate?) 

From reading your last comment, I can agree that is is a duplicate of #13 

Closing this topic
