### ISSUE TITLE
Events added to EvensStream via constructor not marked as new

### ISSUE THREAD

**Issue by sorenmalling** [neos/Neos.EventStore#20]
Is it intended behavior, that new events added to the EventStream is not marked as new, similar to the `addEvent` method?

```
$eventStream = new EventStream([
			new AccountAuthenticated($authenticationToken->getAccount()->getAccountIdentifier(), $authenticationToken->getAuthenticationProviderName())
		]);

		/** @var EventHandlingService $eventHandling */
		$eventHandling = $this->objectManager->get(EventHandlingService::class);
		$eventHandling->publish('es_stream', $eventStream);
```

The `AccountCreated` event is not added to `new` events.

Solution could be to loop the given `events` in the constructor argument and call `addEvent` on each event.

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#41
