### ISSUE TITLE
Event serialization / unserialization

### ISSUE THREAD

**Issue by dfeyer** [neos/Neos.EventStore#4]
So we need a good way to un/serialize events. I prefer to have a language agnostic serialization format (JSON, MessagePack, Protobuf, ...) to be able to consume event in different language.

1. We need to use the PropertyMapper
2. External dependency or not
3. Choose a format
4. What if event contains objects / Did we enforce that event should contain only scalar value + some simple object like DateTime ?

**Comment by dfeyer** [comment]
As we work with Go and Nats since some month, I have to say ProtoBuf is really impressive as a protocol to exchange message. Unfortunately the PHP support is bad as hell.

**Comment by dfeyer** [comment]
Just for reference the beginning of the discussion on Slack: https://neos-project.slack.com/archives/guild-cqrs/p1473932964000348

**Comment by albe** [comment]
I would prefer JSON as default for easyness of use (and reading) but would be cool to have a simple way to switch to "better" formats like Protobuf.

**Comment by dfeyer** [comment]
@albe So for the serialization we should use the ObjectAccess::getGettableProperties and store the event name in some metadata, and store just this array, right ? We can throw an exception is the event contains unsupported types for now.

**Comment by albe** [comment]
yeah, something along those lines. I think @akii did pretty much the same in https://github.com/etg24/EventSourcing

**Comment by dfeyer** [comment]
@albe When i see the mess i create with the PropertyMapper and the nice an clean code that akii did in the etg24 package, I have the feeling that I prefer clean code ... or need to understand a bit more the property mapper ;)

**Comment by albe** [comment]
I don't think akii would mind if we take some inspiration from his serialization implementation ;)

**Comment by dfeyer** [comment]
I'm doing that exactly now ;)

**Comment by albe** [comment]
btw, we could maybe even just use the ArrayFromObjectConverter directly. That *should* already work for recursively converting objects to an array, then use a wrapper converter that does an additional json_encode

**Comment by dfeyer** [comment]
that break on MessageDate try to call the has method ... without argument ..

**Comment by albe** [comment]
Ahhh... I think you actually just found a bug in the ObjectAccess.

**Comment by dfeyer** [comment]
After midnight I have a really special way of handling bug: https://github.com/neos/Neos.Cqrs/commit/636c48078f3bf29df709d37422904a0564783d31

By the way in make sense to call this method contains ;) ... but yes this is a bug in the ObjectAccess

**Comment by albe** [comment]
https://github.com/neos/flow-development-collection/pull/513 just fyi

**Comment by dfeyer** [comment]
We don't use the PropertyMapper, simple gettable properties to json, some improvement are pending in https://github.com/neos/Neos.EventStore/pull/17

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#36
