### ISSUE TITLE
Async Event dispatching and the EventStore

### ISSUE THREAD

**Issue by albe** [neos/Neos.EventStore#8]
Greg Young and a couple of others state that the EventStore itself can work as an Event dispatcher/bus, because it basically works like a queue if you just keep an index of where you last dispatched from.

A similar discussion was started in #2 which I'd like to contiue here:

> you want the events to be published within the same transaction

I think I read that too somewhere, but I must say I'm not convinced. My reasoning mainly is, that the publishing of the events can be retried at any time anyway.
The events become a fact, the instant they are written to permanent storage. Everything happening afterwards is **conceptually eventual consistent**. Binding the dispatching of the events into the same transaction would mean, that if dispatching fails for whatever reason, the eventstore would need to be rolled back. This is wrong on so many levels I can't even express it.

What I do think is a required contract though, is to guarantee **at-least-once** delivery of the events. But that just means to keep a secondary index of events that have already been (successfully) dispatched as stated above.

Probably someone will state that there are cases where you *need* an immediately consistent read model. I'd argue to reconsider your case. Do you **really** need **immediate** consistency, or is it just that you want to work with a projected state *within the same request*? That's quite a difference!

Also if you only need the immediately consistent projected state for some aggregate behaviour, check if you shouldn't put the projected state *into* your aggregate. For all other cases I guess our current in-process EventBus is good enough, so it only needs to be selectively available (ie. through some `InprocessEventListenerInterface`).

The (default?) async behaviour would instead query the EventStore from it's last position cronically (cron CLI command maybe), then dispatch the events to all EventListenerInterfaces.

**Comment by bwaidelich** [comment]
It might be a lack of coffee on my side, but I don't really get what you are suggesting?

**Comment by bwaidelich** [comment]
To clarify what I meant with the phrase you quoted:
I meant that you want the event to be *stored* atomically and I think we're completely on the same track on that: Before the event is published to the store it has no value to the system. So it should go to the store _first_ and within the same transaction.

Whether those published events are handled sync or async could well be abstracted through different busses etc

**Comment by albe** [comment]
Bear with me, I'm always good in overcomplicating things with my writing :)

What I mean is, "within the same transaction" implicates that if **anything** inside that transaction **fails** (store or dispatch), **everything** needs to be **rolled back**. But I don't see an already successful store being rolled back because the dispatch failed.

**Comment by bwaidelich** [comment]
OK, that was a bit misleading. I never thought of any rollback (especially not of published events).
It _can_ be useful to publish more than one event within a transaction (including rollback on failure) but that's a different topic I guess

**Comment by albe** [comment]
OK, so you weren't using the term **transaction** in the technical definition kind of way (https://en.wikipedia.org/wiki/Transaction_processing), but were rather talking about "within the same request", correct?

So we agree that the process inside a single Request is:

```
Transaction Begin:
  Aggregate::executeSomeCommand(...)
  EventStore::commit(Aggregate::pullUncommittedEvents())
Transaction End.
try EventBus::dispatchUndispatchedEvents()
```

The Aggregate::executeSomeCommand being in a transaction with the EventStore commit is only conceptually, because the commit is never triggered if the Aggregate fails, and if the commit fails, the Aggregates uncommitted Events will be lost anyway on the next Request.

But: If the dispatch fails, it can be reattempted at the next Request or by a cronjob or whatever - it just holds a reference to the last commitId of the EventStore that it already dispatched successfully.

The latter only would need to be transactional if you want a strongly/immediate consistent Projection. We *could* implement this when it's explicitly asked for (not trivial), but the default should always be an eventual consistent projection model IMO.

**Comment by bwaidelich** [comment]
> OK, so you weren't using the term transaction in the technical definition [...] but were rather talking about "within the same request", correct?

Well, what I meant is: You want to ensure that the event is actually published to the store within an atomic process. In other words: `$someAggregateRepository->save($someAggregate)` should immediately halt with an exception if events couldn't be stored for some reason.
In (yet) other words: The line after `$someCommandHandler->handleSomeCommand($someCommand)` you know the events in question have been stored for good.

And, yes, I agree to your process description: If there are multiple events* those should be published _transactional_. And dispatching via the EventBus must _not_ be part of the transaction.

* I don't think that there will ever be more than one unpublished event in an aggregate, but sometimes you need to transactionally publish multiple events of multiple aggregates – at least I haven't found a good way around this in some rare scenarios

**Comment by albe** [comment]
Then we're on the same track with that, nice :)

**Comment by bwaidelich** [comment]
This issue was moved to neos/Neos.Cqrs#37
